api_platform:
    formats:
        json: ['application/json']

    patch_formats:
        json: ['application/merge-patch+json']

    title: Hello API Platform
    version: 1.0.0

    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
