doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        #server_version: '10.6' # à adapter selon MariaDB

        profiling_collect_backtrace: '%kernel.debug%'

    orm:
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore

        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity

        auto_mapping: false

        mappings:

            # 🔹 Module Logs
            Logs:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Logs/Entity'
                prefix: 'App\Logs\Entity'
                alias: Logs

            # 🔹 Module principal (si encore utilisé)
            App:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

            # 🔹 Exemple futur module (à activer plus tard)
            # User:
            #     is_bundle: false
            #     type: attribute
            #     dir: '%kernel.project_dir%/src/User/Entity'
            #     prefix: 'App\User\Entity'
            #     alias: User
