doctrine:
    dbal:
        default_connection: default

        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'

            auth:
                url: '%env(resolve:DATABASE_AUTH_URL)%'


    orm:
        default_entity_manager: default

        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore
                mappings:
                    App:
                        type: attribute
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App

            auth:
                connection: auth
                naming_strategy: doctrine.orm.naming_strategy.underscore
                mappings:
                    Auth:
                        type: attribute
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Auth/Entity'
                        prefix: 'App\Auth\Entity'
                        alias: Auth

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            entity_managers:
                default:
                    query_cache_driver:
                        type: pool
                        pool: doctrine.system_cache_pool
                    result_cache_driver:
                        type: pool
                        pool: doctrine.result_cache_pool

                auth:
                    query_cache_driver:
                        type: pool
                        pool: doctrine.system_cache_pool
                    result_cache_driver:
                        type: pool
                        pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app

                doctrine.system_cache_pool:
                    adapter: cache.system