# config/packages/doctrine.yaml

doctrine:
  dbal:
    default_connection: api

    connections:
      auth:
        url: '%env(resolve:DATABASE_AUTH_URL)%'

      api:
        url: '%env(resolve:DATABASE_API_URL)%'

  orm:
    default_entity_manager: api

    entity_managers:

      auth:
        connection: auth
        mappings:
          Auth:
            is_bundle: false
            dir: '%kernel.project_dir%/src/Auth/Entity'
            prefix: 'App\Auth\Entity'

      api:
        connection: api
        mappings:

          Logs:
            is_bundle: false
            dir: '%kernel.project_dir%/src/Api/Logs/Domain/Entity'
            prefix: 'App\Api\Logs\Domain\Entity'
