monolog:
    handlers:

        main:
            type: stream
            path: "%kernel.logs_dir%/app.log"
            level: debug
            formatter: monolog.formatter.json

        error:
            type: stream
            path: "%kernel.logs_dir%/error.log"
            level: error
            formatter: monolog.formatter.json

        business:
            type: stream
            path: "%kernel.logs_dir%/business.log"
            level: info
            channels: ["business"]
            formatter: monolog.formatter.json

        console:
            type: console
            process_psr_3_messages: false
