monolog:
    channels: ['business', 'technical', 'fallback']

    handlers:

        # =========================
        # 🔧 TECHNICAL LOGS
        # =========================
        technical:
            type: stream
            path: "%kernel.logs_dir%/technical.log"
            level: debug
            channels: ["technical"]
            formatter: App\Shared\Logging\Infrastructure\Monolog\UtcJsonFormatter

        # =========================
        # 💼 BUSINESS LOGS
        # =========================
        business:
            type: stream
            path: "%kernel.logs_dir%/business.log"
            level: info
            channels: ["business"]
            formatter: App\Shared\Logging\Infrastructure\Monolog\UtcJsonFormatter

        # =========================
        # ❌ ERROR GLOBAL
        # =========================
        error:
            type: stream
            path: "%kernel.logs_dir%/error.log"
            level: error
            formatter: App\Shared\Logging\Infrastructure\Monolog\UtcJsonFormatter

        # =========================
        # 🚀 API LOGS → QUEUE
        # =========================
        api_logs_technical:
            type: service
            id: App\Shared\Logging\Infrastructure\Monolog\BufferedApiLogsHandler.technical
            level: error
            channels: ["technical"]

        api_logs_business:
            type: service
            id: App\Shared\Logging\Infrastructure\Monolog\BufferedApiLogsHandler.business
            level: info
            channels: ["business"]

        # =========================
        # 🛟 FALLBACK
        # =========================
        fallback:
            type: stream
            path: "%kernel.logs_dir%/api_fallback.log"
            level: error
            channels: ["fallback"]
            formatter: App\Shared\Logging\Infrastructure\Monolog\UtcJsonFormatter

        # =========================
        # 🖥️ CONSOLE
        # =========================
        console:
            type: console
            process_psr_3_messages: false
