security:

    password_hashers:
        App\Auth\Entity\User:
            algorithm: auto

    providers:
        auth_user_provider:
            entity:
                class: App\Auth\Entity\User
                property: email

    firewalls:

        # 🔧 DEV (profiler, assets…)
        dev:
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false

        # 🌐 API DOMAIN
        api:
            pattern: ^/
            host: '%env(API_HOST_REGEX)%'
            security: false

        # 🌐 AUTH DOMAIN
        auth:
            pattern: ^/
            host: '%env(AUTH_HOST_REGEX)%'
            security: false

    access_control: [ ]
