security:

    password_hashers:
        App\Auth\Entity\User:
            algorithm: auto

    providers:
        auth_user_provider:
            entity:
                class: App\Auth\Entity\User
                property: email

    firewalls:

        # 🔧 DEV (profiler, assets…)
        dev:
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false

        # 🔐 API (stateless JWT)
        api:
            pattern: ^/api
            stateless: true
            jwt: ~

        # 🔓 AUTH (login + session)
        auth:
            pattern: ^/
            provider: auth_user_provider
            lazy: true
            stateless: false

            form_login:
                login_path: /login
                check_path: /login

            logout:
                path: /logout

    access_control:

        # =========================
        # 🔐 API (PRIORITAIRE)
        # =========================
        - { path: ^/api/logs, roles: ROLE_LOGS }
        # - { path: ^/api/corbycats, roles: ROLE_CAT }

        # =========================
        # 🔓 AUTH
        # =========================
        - { path: ^/login, roles: PUBLIC_ACCESS }

        # =========================
        # 🔒 AUTRES ROUTES AUTH
        # =========================
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
