# config/routes.yaml

controllers:
    resource: ../src/Controller/
    type: attribute

api_platform:
    resource: routes/api_platform.yaml

# =========================
# 🔓 AUTH
# =========================
auth:
    resource: routes/auth.yaml

# =========================
# 📊 API LOGS
# =========================
# api:
#     resource: routes/api.yaml

api_admin:
  resource: '../src/Api/Jwt/Controller/'
  type: attribute
##  host: '%api_host%'

