# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

# =========================
# 🔓 AUTH
# =========================
auth_controllers:
    resource: ../src/Auth/Controller/
    type: attribute

# =========================
# 🔐 API LOGS
# =========================
api_logs_controllers:
    resource: ../src/Api/Logs/Controller/
    type: attribute
    prefix: /api/logs

# =========================
# 🐱 API CORBYCATS
# =========================
#api_corbycats_controllers:
#    resource: ../src/Api/Corbycats/Controller/
#    type: attribute
#    prefix: /api/corbycats
