parameters:
    auth_host: '%env(AUTH_HOST)%'
    api_host: '%env(API_HOST)%'
    cron_token: '%env(CRON_TOKEN)%'

services:

    _defaults:
        autowire: true
        autoconfigure: true

    # =========================
    # 🔥 Chargement automatique de l'app
    # =========================
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Kernel.php'

    # =========================
    # 🧠 Cache Tenant
    # =========================
    tenant.cache:
        class: Symfony\Component\Cache\Adapter\FilesystemAdapter
        arguments:
            $namespace: 'tenant'
            $defaultLifetime: 3600

    # =========================
    # 📁 File Queue Logs
    # =========================
    App\Api\Logs\Application\Service\FileLogQueueService:
        arguments:
            $dir: '%kernel.project_dir%/var/log_queue'

    # =========================
    # 🧠 Tenant Provider
    # =========================
    App\Api\Logs\Context\TenantProvider:
        arguments:
            $cache: '@tenant.cache'

    # =========================
    # 🔥 API Error Listener (CENTRAL)
    # =========================
    App\EventListener\ApiErrorListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception, priority: 100 }

    # =========================
    # 📊 HTTP Status Provider
    # =========================
    App\Http\HttpStatusProvider:
        arguments:
            $filePath: '%kernel.project_dir%/config/http_statuses.fr.json'
