# config/services.yaml

parameters:

services:

    _defaults:
        autowire: true
        autoconfigure: true

    # 🔥 Chargement global
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Kernel.php'

    # =========================
    # 🧠 Cache Tenant
    # =========================
    tenant.cache:
        class: Symfony\Component\Cache\Adapter\FilesystemAdapter
        arguments:
            $namespace: 'tenant'
            $defaultLifetime: 3600

    # =========================
    # 📊 Logs - TenantProvider
    # =========================
    App\Api\Logs\Context\TenantProvider:
        arguments:
            $cache: '@tenant.cache'
