# routes/dev.yaml
auth:
  resource: ../../src/Auth/Controller/
  type: attribute
  host: '%auth_host%'

api_logs:
  resource: ../../src/Api/Logs/Controller/
  type: attribute
  prefix: /api/logs
  host: '%api_host%'
