# Ce workflow déploie automatiquement sur le serveur PROD après merge dans main

name: 🚀 Déploiement PROD Logs

on:
  pull_request:
    branches: [ main ]
    types: [ closed ]

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: prod-deploy-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  deploy-prod:
    name: 🚀 Déploiement PROD Logs
    if: |
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true) ||
      (github.event_name == 'workflow_dispatch')
    uses: LeZouzouEnWeb/workflows/.github/workflows/deploy-logs.yml@v1.0.14
    permissions:
      contents: write
      pull-requests: write
    secrets:
      REMOTE_CHEMIN: ${{ secrets.REMOTE_CHEMIN }}
      SFTP_HOST: ${{ secrets.SFTP_HOST }}
      SFTP_USER: ${{ secrets.SFTP_USER }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    with:
      ADRESSE_GLOBAL: ${{ vars.ADRESSE_GLOBAL }}
      ADRESSE_LOCAL: ${{ vars.ADRESSE_LOCAL }}
      remote_env: 'prod'
      enable_mirror: false
